name = "LinearAlgebraCourse"
version = "0.1.0"
keywords = ["math", "linear-algebra", "lean"]
defaultTargets = ["LinearAlgebra"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "7d32461ad224e921eb05ead7ac02156702f4aa59"

[[lean_lib]]
name = "LinearAlgebra"
